### PR TITLE
libcextract: SymbolExternalizer: Drop klpe_ prefix if IBT is specified

### PR DESCRIPTION
**Pull request by marcosps**
The resulting code would be exactly the same as the original code, or at least as much as it can be the same.

### CODE REVIEW

**Review by giulianobelinassi — CHANGES_REQUESTED** [review]
It is not that simple. The way you are doing this you are going to update every reference to the function or variable with a new name that is equal to the name of the old function. That is unnecessary and will result in unnecessary header expansions. You should instead skip the update of those symbols.

And please rebase it on top of the latest branch, as this conflicts with the LateExternalization :) .

**Comment by marcosps** [comment]
> It is not that simple. The way you are doing this you are going to update every reference to the function or variable with a new name that is equal to the name of the old function. That is unnecessary and will result in unnecessary header expansions. You should instead skip the update of those symbols.
> 
> And please rebase it on top of the latest branch, as this conflicts with the LateExternalization :) .

But I still need to include the outstr, to add the KLP_RELOC_SYMBOL macro. Or can I just add these symbols at the end like I'm doing for klp-ccp?

In not like this, how can I add the symbol to the final closure without rewriting it, and still adding the `extert` ... `KLP_RELOC_SYMBOL` macro?

**Comment by marcosps** [comment]
@giulianobelinassi please take a look in this new version of the patch. I found some issues with this approach, because it seems that it trigger different header expansion to some LPs tested (thanks to my klp-build test.sh script now I can test if changes like this ripple over previously working LPs...)

I'm sure that I'm forgetting something...

**Comment by marcosps** [comment]
This one was superseded by #101

**Pull request closed without merging**
