### PR TITLE
testsuite/small: Adapt tests to s390.

### PR DESCRIPTION
**Pull request by marcosps**

### CODE REVIEW

**Comment by marcosps** [comment]
@giulianobelinassi these have been the only tests that failed when I run the tests on one s390 testing machine. @ggardet unfortunately I couldn't reproduce the other issues in a physical machine, only these two failed to me. DO you know if running these on VMs make it to fail?

Thanks!

**Comment by giulianobelinassi** [comment]
Those two tests are supposed to check for a very special kind of attribute, which are `asm(reg)` attributes specified in variables. I say special because those attributes can not be defined on the left hand side of a declaration, only on the right side.

I am sorry, but the code you wrote doesn't test it at all. So you can either skip the test (e.g. patch libtest to specify some keyword like { dg-skip-if <REGEX> }, and then see if the REGEX matches the architecture in which the tests are run. For example, this line:
```
/* { dg-skip-if "attribute ((aligned))" { ! { i?86-*-* x86_64-*-* } } } */
```
makes GCC skip the test if not run on ix86 or x86_64. Something similar can be implemented on our side.

**Review by giulianobelinassi — CHANGES_REQUESTED** [review]
See previous comment

**Comment by marcosps** [comment]
Ok, let me do it :)

**Comment by marcosps** [comment]
@giulianobelinassi we now have an option to skip tests based on their architecture. It word when I specified x86_64 in my machine, so I hope it would also work on OBS for s390x cases reported.

**Comment by marcosps** [comment]
@ggardet could you please test if this patchset makes these tests to be skipped on s390x? thanks in advance!

**Pull request merged**
